port: 7789
scrape_frequency: 1
user : "login"
password : "password!"
label : "NSXv3"
url_list : 
  - link : "https://op-nsx-manager-dcf1.oncloud.host"
    name : ""
check_list:
  - link : "https://op-nsx-manager-dcf1.oncloud.host"
    name : ""
    word: "DOWN"
